

# This file was *autogenerated* from the file round.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_10 = Integer(10)
import sys
load("../rounding_Integer.sage")
round_program("SDP_n"+sys.argv[_sage_const_1 ]+"_LB_F_ordered_edges3__objective.txt.dat-s",scale=_sage_const_10 )
'''
Result:
Minimum (after unscaling) found at 5694 / 6001 Value is 0.03906345111431516
390634511143151657709439378392479666426456 / 10000000000000000000000000000000000000000000  # =  0.03906345111431517
'''

