

# This file was *autogenerated* from the file round.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_10 = Integer(10)
import sys
load("/home/sydney/flags/rounding_Integer.sage")
round_program("SDP_n"+sys.argv[_sage_const_1 ]+"_LB_F_ordered_edges3__objective.txt.dat-s", scale=_sage_const_10 )
'''
Minimum (after unscaling) found at 5220 / 6001 Value is 0.049373125291256904
493731252912569049880850675641866424932636 / 10000000000000000000000000000000000000000000  # =  0.049373125291256904
'''

