

# This file was *autogenerated* from the file round.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10 = Integer(10); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_30 = Integer(30)
import sys
load("../rounding_Integer.sage")
S = _sage_const_10 
if int(sys.argv[_sage_const_1 ]) == _sage_const_6 :
	S = _sage_const_30 
round_program("SDP_n" + str(sys.argv[_sage_const_1 ]) + "_LB_F_ordered_edges3__objective.txt.dat-s",scale=S)
'''
Result:
Minimum (after unscaling) found at 5936 / 6001 Value is 0.03746387918200873374638791820087306596553119645636250748306 / 10000000000000000000000000000000000000000000  # =  0.03746387918200873
'''

