

# This file was *autogenerated* from the file round.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_10 = Integer(10)
import sys
load("../rounding_Integer.sage")
round_program("SDP_n"+sys.argv[_sage_const_1 ]+"_LB_F_ordered_edges3__objective.txt.dat-s",scale=_sage_const_10 )
'''
Result:
Minimum (after unscaling) found at 3773 / 6065 Value is 0.020166009528582995
201660095285829954691538561448176407569728 / 10000000000000000000000000000000000000000000  # =  0.020166009528582995
'''

